 
PrakrutiData = {
       'Skin color': 1,
        'Skin texture': 1,
        'Details about hair type': 1,
        'Texture of hair ': 1,
        'My hairs are': 1,
        'Hair falling tendency\t': 1,
        'Eyes\t': 1,
        'My eyes  eye balls are': 1,
        'Physique\t': 1,
        'Veins\t': 1,
        'Usual body temperature \t': 1,
        'Teeth \t': 1,
        'Is your lips\t': 2,
        'Hands(Length)': 2,
        'Body hair\t': 2,
        'Joints\t': 2,
        'Chest\t': 2,
        'Tongue\t': 2,
        'Body frame (Length)\t': 2,
        'Body frame (Breadth)\t': 2,
        'Bodyweight changes\t': 2,
        'Style of speaking\t': 2,
        'Voice \t': 2,
        'Walk \t': 2,
        'Appetite \t ': 2,
        'Intensity of hunger\t': 2,
        'Favorite climate\t': 2,
        'Stamina\t': 2,
        'Tastes, I like most': 2,
        'Eagerness about drinking water': 2,
        'Frequency of liquid intake\t': 2,
        'Sleep\t': 2,
        'Quantity of sweat\t': 2,
        'Emotion\t': 2,
        'Intellect\t': 2,
        'Grasping\t': 2,
        'Concentration\t': 2,
        'Memory\t': 2,
        'Temperament\t': 2,
        'Patience\t': 2,
        'Satisfaction/content\t': 2,
        'While making decisions\t': 2,
        'Activities\t': 2,
        'Nature of dreams\t': 2,
        'Friendships & relations\t': 2,
        'Faith in God\t': 2,
        'Self-control\t': 2,
        'Gratefulness\t': 2,
        'Likings\t': 2,
        'Liking- type of food': 2,
        'Politeness/humbleness':2,
        'Biting nails ': 1,
        'Fond of praise ': 1,
        'Brave': 1,
        'Egoistic': 1
    }